`timescale 1ns / 1ps

module Alu_16_bit(
    input  [15:0] A,
    input  [15:0] B,
    input  [3:0]  imm,
    input  carry_in,// Old CF from flag register
    input  [3:0]  ALU_op,
    input  [3:0]  ALU_sub_op,
    input  B_select_imm,//im conserding every sub_op code lsb to be associate with decision of whether its a,b or a,imm
    input  use_carry_in, // signal generated by instruction decode which will say if its ADCS OR SBB THEN use carry in
    input  mul_signed,
    input  cmp_signed,
    output [15:0] Y,
    output  carry_out,
    output  overflow,
    output  zero,
    output  sign,
    output  GT,
    output  LT,
    output  EQ
);

    wire [15:0] imm_16;
    assign imm_16 = {12'b0, imm};
    wire [15:0] operand_B;

    assign operand_B = B_select_imm ? imm_16 : B;
    wire [15:0] add_result;
    wire  add_carry;

    wire add_cin;
    assign add_cin =use_carry_in ? carry_in : 1'b0;
    wire add_cin_msb;
    Cska_adder16_bit cska1 (
        .A(A),
        .B(operand_B),
        .Cin(add_cin),
        .Sum(add_result),
        .Cout(add_carry),
        .Cin_msb(add_cin_msb)
    );
    wire add_overflow ;
    assign add_overflow = add_carry ^ add_cin_msb;
    wire [15:0] sub_result;
    wire sub_borrow;
    wire sub_bin;
    assign sub_bin =use_carry_in ? carry_in : 1'b0;
    wire sub_bin_msb;
    cska_16bit_sub sub1 (
        .A(A),
        .B(operand_B),
        .Bin(sub_bin),
        .Diff(sub_result),
        .Bin_msb(sub_bin_msb),
        .Bout(sub_borrow)
    );
    wire sub_overflow;
    assign sub_overflow = sub_borrow ^ sub_bin_msb;
    wire [15:0] mul_result;
    booth_multiplier_16bit multiplier1 (
        .A(A),
        .B(operand_B),
        .is_signed(mul_signed),
        .out(mul_result)
    );
    cmp_16_usingsub comparator1 (
        .A(A),
        .B(operand_B),
        .is_signed(cmp_signed),
        .BGT(GT),
        .BLT(LT),
        .BEQ(EQ)
    );
    
   wire [15:0] shift_result;
    shifter_unit_combine shift1 (
        .data(A),
        .shift_amt(operand_B),
        .shift_type(ALU_sub_op[3:1]),//last bit of alu_sub_op denotes if operation is with B reg or imm
        .out(shift_result)
    );
    reg [15:0] result_reg;
    reg  carry_reg;
    reg  overflow_reg;
    assign Y  = result_reg;
    assign carry_out = carry_reg;
    assign overflow = overflow_reg;
    assign zero = (result_reg == 16'b0);
    assign sign = result_reg[15];
   always @(*) begin

        result_reg = 16'b0;
        carry_reg  = 1'b0;
        overflow_reg = 1'b0;

        case (ALU_op)
            4'b0000: begin
                result_reg = add_result;
                carry_reg  = add_carry;
                overflow_reg = add_overflow;
            end
            4'b0001: begin
                result_reg = sub_result;
                carry_reg  = sub_borrow;
                overflow_reg = sub_overflow;
            end
            4'b0010: result_reg = A & B;
            4'b0011:result_reg = A | B;
            4'b0100:result_reg = A ^ B;
            4'b0101: result_reg = ~A;
            4'b0110: result_reg = mul_result;
            4'b0111: result_reg = 16'b0;
            4'b1000:  result_reg = shift_result;
            default: begin
                result_reg = 16'b0;
                carry_reg    = 1'b0;
                overflow_reg = 1'b0;
              end
        endcase
    end
endmodule
