`timescale 1ns / 1ps

module control_unit(
input [15:0] instruction,
input Z,N,C,V, //these are comparator generated outputs and need to be recieved from comparator ouputs only .and later based on opcode we will decide
//whether to use comparator as our flag update source or alu add and sub// flags from the flag register
input EQ,GT,LT,// flags signals coming directly from comparaator so beq,blt,bgt must be done after the comparator is done
output reg B_operand,// select what will be the b operand(register value or immediate) in operation of a and b
output reg wr_signal,
output reg use_carry_flg, // for adcs and sbb we need borrow and carry in
output reg[2:0] shift_type,
output reg [3:0]alu_op,
output reg [3:0] extract_imm,
output reg branching,
output reg[7:0] offset,//jump amount for pc
output reg flag_write,
output reg flag_source,
output reg cmp_signed,
output reg mul_signed,
output reg mem_read,
output reg mem_write,
output reg mem_to_reg,
output reg halt_pc,//will be given as input to pc in datapath's pc instantiation .generated by opcode 0 and 15
output reg reset_pc
    );
wire [3:0]opcode,sub_op;
assign opcode = instruction[15:12];
assign sub_op = instruction[11:8];
always @(*)begin
B_operand = 1'b0;
branching = 1'b0;
offset = 8'b0;
wr_signal = 1'b0;
use_carry_flg = 1'b0;
shift_type = 3'b000;
alu_op = 4'b0000;
extract_imm = 4'b0000;
flag_write = 1'b0;
cmp_signed = 1'b0;
flag_source = 1'b0;
mem_read = 1'b0;
mem_write = 1'b0;
mem_to_reg = 1'b0;
halt_pc = 1'b0;
reset_pc = 1'b0;
mul_signed = 1'b0;
  case(opcode)
   4'b0100:begin // ADD
      case(sub_op)
      4'b0000:begin// SIMPLE ADD R1,R2
         B_operand = 1'b0;// why i will interface this with b_select_imm of alu which selects imm when 1
         wr_signal = 1'b1;
         use_carry_flg = 1'b0; // for add with carry or sub with borrow
         alu_op = 4'b0000;
      end
      4'b0001:begin//  ADC R1,R2
         B_operand = 1'b0;// why i will interface this with b_select_imm of alu which selects imm when 1
         wr_signal = 1'b1;
         use_carry_flg = 1'b1; // for add with carry or sub with borrow
         alu_op = 4'b0000;
      end   
      4'b0010:begin// ADI R1,#IMM
         B_operand = 1'b1;
         wr_signal = 1'b1;
         use_carry_flg = 1'b0;
         alu_op = 4'b0000;   
         extract_imm = instruction[3:0];
      end 
     endcase
    end
  4'b0011:begin
    case(sub_op)
        4'b0000: begin // L-shift R1, R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            shift_type = 3'b000;
            alu_op = 4'b1000;
         
        end
        4'b0001: begin // L-shift R1, imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            shift_type = 3'b000;
            alu_op = 4'b1000;
            extract_imm = instruction[3:0];
        end
        4'b0010: begin   // r-shift R1, R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            shift_type = 3'b001;
            alu_op = 4'b1000;
           
        end
        4'b0011: begin// R-shift R1, #imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            shift_type = 3'b001;
            alu_op = 4'b1000;
            extract_imm = instruction[3:0];
        end
        4'b0100: begin// A-shift R1, R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            shift_type = 3'b010;
            alu_op = 4'b1000;
            
        end
        4'b0101: begin // A-shift R1, #imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            shift_type = 3'b010;
            alu_op = 4'b1000;
            extract_imm = instruction[3:0];
        end
        4'b0110: begin   // R-rotate R1, R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            shift_type = 3'b011;
            alu_op = 4'b1000;
            
        end
        4'b0111: begin  // R-rotate R1, #imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            shift_type = 3'b011;
            alu_op = 4'b1000;
            extract_imm = instruction[3:0];
        end
        4'b1000: begin  // L-rotate R1, R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            shift_type = 3'b100;
            alu_op = 4'b1000;
            
        end

        4'b1001: begin // L-rotate R1, #imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            shift_type = 3'b100;
            alu_op = 4'b1000;
            extract_imm = instruction[3:0];
        end
    endcase
end
  4'b0010:begin
  case(sub_op)
    4'b0000:begin//unconditional jump
    branching = 1'b1;
    offset= instruction[7:0];
    end
    4'b0001:begin
    branching= Z? 1'b1 : 1'b0;
    offset= instruction[7:0];
    end  
    4'b0010:begin
    branching= Z? 1'b0 : 1'b1;
    offset= instruction[7:0];
    end  
    4'b0011:begin
    branching= C? 1'b1 : 1'b0;
    offset= instruction[7:0];
    end  
    4'b0100:begin
    branching= C? 1'b0 : 1'b1;
    offset= instruction[7:0];
    end  
    4'b0101:begin
    branching= V? 1'b1 : 1'b0;
    offset= instruction[7:0];
    end  
    4'b0110:begin
    branching= V? 1'b0 : 1'b1;
    offset= instruction[7:0];
    end  
    4'b1010:begin
    branching= GT? 1'b1 : 1'b0;
    offset= instruction[7:0];
    end  
    4'b1011:begin
    branching= LT? 1'b1 : 1'b0;
    offset= instruction[7:0];
    end  
    4'b1000:begin//BEQ
    branching= EQ? 1'b1 : 1'b0;
    offset= instruction[7:0];
    end  
    4'b1001:begin//BNE
    branching= EQ? 1'b0 : 1'b1;
    offset= instruction[7:0];
    end  
    4'b1100:begin//BGE -GREATER THAN OR EQUAL TO
    branching= (GT | EQ)? 1'b1 : 1'b0;
    offset= instruction[7:0];
    end  
    4'b1101:begin// BLE- LESS THAN OR EQUAL TO
    branching= (LT | EQ)? 1'b1 : 1'b0;
    offset= instruction[7:0];
    end  
    4'b1110:begin//cmp
    cmp_signed = 1'b0;
    flag_write = 1'b1;
    flag_source = 1'b1;
    alu_op = 4'b0111;
    end
    4'b1111:begin//cmps
    cmp_signed = 1'b1;
    flag_write = 1'b1;
    flag_source = 1'b1;
    alu_op = 4'b0111;
    end  
    
  endcase  
 end 
 4'b0001:begin// mov
 case(sub_op)
           4'b0000:begin // MOV R1,R2
                B_operand = 1'b0;
                wr_signal = 1'b1;
                alu_op = 4'b1001;
            end
    
            4'b0001:begin // MOV R1,#imm
                B_operand = 1'b1;
                wr_signal = 1'b1;
                extract_imm = instruction[3:0];
                alu_op = 4'b1001;
            end

    endcase
end
4'b0101:begin //load,LOAD  R1, [R2]  
 case(sub_op)
 4'b0001:begin
    B_operand = 1'b0;
    mem_read = 1'b1;
    mem_to_reg = 1'b1;
    wr_signal = 1'b1;
  end
 endcase
end  
4'b0110:begin
 case(sub_op)//str [r1],r2
 4'b0001:begin
    B_operand = 1'b0;
    mem_write = 1'b1;
    wr_signal = 1'b0;
 end 
 4'b0010:begin//str [r1],imm
     B_operand = 1'b1;
     mem_write = 1'b1;
     wr_signal = 1'b0;
     extract_imm = instruction[3:0];
   end
 endcase
end 
4'b0000:begin
 case(sub_op)
 4'b0000:reset_pc = 1'b1;
 endcase
end
4'b1111:begin
  case(sub_op)
   4'b0000:halt_pc = 1'b1;
   endcase
end   
4'b1000:begin // AND
    case(sub_op)
        4'b0000:begin // AND R1,R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            alu_op = 4'b0010;
        end
        4'b0001:begin // AND R1,#imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = instruction[3:0];
            alu_op = 4'b0010;
        end
    endcase
end
4'b1011:begin // OR
    case(sub_op)
        4'b0000:begin // OR R1,R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            alu_op = 4'b0011;
        end
        4'b0001:begin // OR R1,#imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = instruction[3:0];
            alu_op = 4'b0011;
        end
    endcase
end

4'b1010:begin // XOR
    case(sub_op)
        4'b0000:begin // XOR R1,R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            alu_op = 4'b0100;
        end
        4'b0001:begin // XOR R1,#imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = instruction[3:0];
            alu_op = 4'b0100;
        end
    endcase
end

4'b1001:begin // NOT
    case(sub_op)
        4'b0000:begin // NOT R1
            B_operand = 1'b0;
            wr_signal = 1'b1;
            alu_op = 4'b0101;
        end
    endcase
end   
4'b1100:begin // MUL
    case(sub_op)
        4'b0000:begin // MUL R1,R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            mul_signed = 1'b0;
            alu_op = 4'b0110;
        end
        4'b0001:begin // MUL R1,#imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            mul_signed = 1'b0;
            extract_imm = instruction[3:0];
            alu_op = 4'b0110;
        end
    endcase
end
4'b1101:begin // MULS
    case(sub_op)
        4'b0000:begin // MULS R1,R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            mul_signed = 1'b1;
            alu_op = 4'b0110;
        end
        4'b0001:begin // MULS R1,#imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            mul_signed = 1'b1;
            extract_imm = instruction[3:0];
            alu_op = 4'b0110;
        end
    endcase
end   
4'b0111:begin // SUB
    case(sub_op)
        4'b0000:begin // SUB R1,R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            use_carry_flg = 1'b0;
            alu_op = 4'b0001;
        end

        4'b0001:begin // SBB R1,R2
            B_operand = 1'b0;
            wr_signal = 1'b1;
            use_carry_flg = 1'b1;
            alu_op = 4'b0001;
        end

        4'b0010:begin // SUBI R1,#imm
            B_operand = 1'b1;
            wr_signal = 1'b1;
            use_carry_flg = 1'b0;
            extract_imm = instruction[3:0];
            alu_op = 4'b0001;
        end
    endcase
end 
4'b1110:begin // INR / DCR
    case(sub_op)

        4'b0000:begin // ICO +1
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = 4'b0001;
            alu_op = 4'b0000;
        end

        4'b0001:begin // ICT +2
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = 4'b0010;
            alu_op = 4'b0000;
        end

        4'b0010:begin // ICF +4
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = 4'b0100;
            alu_op = 4'b0000;
        end

        4'b0011:begin // ICE +8
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = 4'b1000;
            alu_op = 4'b0000;
        end

        4'b1000:begin // DCO -1
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = 4'b0001;
            alu_op = 4'b0001;
        end

        4'b1001:begin // DCT -2
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = 4'b0010;
            alu_op = 4'b0001;
        end

        4'b1010:begin // DCF -4
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = 4'b0100;
            alu_op = 4'b0001;
        end

        4'b1011:begin // DCE -8
            B_operand = 1'b1;
            wr_signal = 1'b1;
            extract_imm = 4'b1000;
            alu_op = 4'b0001;
        end
       endcase
      end  
    
    endcase
   end
 endmodule